M48
; DRILL file KiCad 10.0.5-10.0.5~ubuntu26.04.1 date 2026-07-31T22:15:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-31T22:15:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5-10.0.5~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X54.1Y-55.35
X54.1Y-170.35
X155.1Y-55.35
X155.1Y-170.3
M30
